DATASET:
  dataset: "None"
  num_label: 0
  mixup: 0.8
  cutmix: 1.0
  reprob: 0.25
  drop_path: 0.2
SOLVER:
  batch: 0
  epoch: 50
  accum_iter: 1
  save_model_epoch: 50
  eval_epoch: 1
  blr: 1e-3
  layer_decay: 0.75
  weight_decay: 0.05
MODEL:
  model: vit_large_patch16
UTIL:
